name: CI Checks

concurrency:
  group: ci-${{ github.ref_name }}
  cancel-in-progress: true

on:
  pull_request:
    types: [ opened, synchronize, reopened, ready_for_review ]

jobs:
  lint-android:
    if: github.event.pull_request.draft == false
    name: Lint Android
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Check out repository
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4

      - name: Set up Java environment
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 17

      - name: Set up Android environment
        uses: android-actions/setup-android@v2

      - name: Lint Android source
        uses: gradle/gradle-build-action@v2
        with:
          arguments: lintDebug

  lint-kotlin:
    if: github.event.pull_request.draft == false
    name: Lint Kotlin
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Check out repository
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4

      - name: Set up Java environment
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 17

      - name: Lint Kotlin code
        uses: gradle/gradle-build-action@v2
        with:
          arguments: lintKotlin

  unit-tests:
    if: github.event.pull_request.draft == false
    name: Unit Tests
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Check out repository
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4

      - name: Set up Java environment
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 17

      - name: Set up Android environment
        uses: android-actions/setup-android@v2

      - name: Run unit tests
        uses: gradle/gradle-build-action@v2
        with:
          arguments: testDebugUnitTest

  android-tests:
    if: github.event.pull_request.draft == false
    name: Android Tests
    runs-on: macos-latest
    timeout-minutes: 30

    steps:
      - name: Check out repository
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4

      - name: Set up Java environment
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 17

      - name: Set up Android environment
        uses: android-actions/setup-android@v2

      - name: Run Android tests (Pixel 7 API 33)
        uses: gradle/gradle-build-action@v2
        with:
          arguments: pixel7Api33DebugAndroidTest -Pandroid.testoptions.manageddevices.emulator.gpu=swiftshader_indirect
